"""add_map_fields_to_table

Revision ID: 1afe9f6b1296
Revises: 2c4515409e62
Create Date: 2025-06-18 06:46:03.080505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afe9f6b1296'
down_revision: Union[str, None] = '2c4515409e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('map_image_url', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('tokens_state', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notify_on_join_request', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_on_request_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notify_on_new_story', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_on_new_story')
    op.drop_column('users', 'notify_on_request_approved')
    op.drop_column('users', 'notify_on_join_request')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('tables', 'tokens_state')
    op.drop_column('tables', 'map_image_url')
    # ### end Alembic commands ###
