"""Add story_id to Table model

Revision ID: 2c4515409e62
Revises: 
Create Date: 2025-06-16 08:50:26.700767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4515409e62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_tables_story_id', 'stories', ['story_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tables_story_id', type_='foreignkey')
        batch_op.drop_column('story_id')
    # ### end Alembic commands ###
