"""Add table request system with character selection and level requirements

Revision ID: ef1bb2e5d535
Revises: eae80ed0c7d6
Create Date: 2025-08-30 09:39:27.554066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1bb2e5d535'
down_revision: Union[str, None] = 'eae80ed0c7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('character_id', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('join_requests', sa.Column('master_response', sa.Text(), nullable=True))
    op.add_column('join_requests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('join_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'join_requests', 'characters', ['character_id'], ['id'])
    op.add_column('tables', sa.Column('max_players', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('min_character_level', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('max_character_level', sa.Integer(), nullable=True))
    op.add_column('tables', sa.Column('scheduled_date', sa.DateTime(), nullable=True))
    op.add_column('tables', sa.Column('location', sa.String(), nullable=True))
    op.add_column('tables', sa.Column('campaign_description', sa.Text(), nullable=True))
    op.add_column('tables', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'is_active')
    op.drop_column('tables', 'campaign_description')
    op.drop_column('tables', 'location')
    op.drop_column('tables', 'scheduled_date')
    op.drop_column('tables', 'max_character_level')
    op.drop_column('tables', 'min_character_level')
    op.drop_column('tables', 'max_players')
    op.drop_constraint(None, 'join_requests', type_='foreignkey')
    op.drop_column('join_requests', 'updated_at')
    op.drop_column('join_requests', 'created_at')
    op.drop_column('join_requests', 'master_response')
    op.drop_column('join_requests', 'message')
    op.drop_column('join_requests', 'character_id')
    # ### end Alembic commands ###
